name: codecov
on: [push]
  # push:
  #   branches:
  #     - main


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Assert changed
        run: ./scripts/assert-changed-files-actions.sh "packages"

      - name: Bootstrap packages
        uses: ./.github/actions/cache-bootstrap
        with:
          extension: unit-tests

      - name: Build Packages
        run: yarn build

      - name: Run unit tests with coverage
        run: yarn test --coverage
        working-directory: ./packages/medusa

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

      

